# Generated by Django 2.0.8 on 2018-11-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181129_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card_ending',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
